export AUTODL_TOKEN="eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjY3MzAyNCwidXVpZCI6IjUxNWEyNzg5ZDgwMzdlZmEiLCJpc19hZG1pbiI6ZmFsc2UsImJhY2tzdGFnZV9yb2xlIjoiIiwiaXNfc3VwZXJfYWRtaW4iOmZhbHNlLCJzdWJfbmFtZSI6IiIsInRlbmFudCI6ImF1dG9kbCIsInVwayI6IiJ9.Z7ehfhzgIStE3_7RTiinhlkYxGA2i1yoPZbWce9DFiQt4iTuenJWJP4V0iT45VGCWTcS43Lw4iZKwYD7APxfzw"
export API_TOKEN="foresee_hq_job"
python -m hq_job.server